minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - eslint-plugin-react-refresh@0.5.6
  - '@antfu/eslint-config@9.5.1'
  - '@eslint-react/ast@5.18.7'
  - '@eslint-react/core@5.18.7'
  - '@eslint-react/eslint-plugin@5.18.7'
  - '@eslint-react/eslint@5.18.7'
  - '@eslint-react/jsx@5.18.7'
  - '@eslint-react/shared@5.18.7'
  - '@eslint-react/var@5.18.7'
  - eslint-plugin-pnpm@1.9.1
  - eslint-plugin-react-dom@5.18.7
  - eslint-plugin-react-jsx@5.18.7
  - eslint-plugin-react-naming-convention@5.18.7
  - eslint-plugin-react-rsc@5.18.7
  - eslint-plugin-react-web-api@5.18.7
  - eslint-plugin-react-x@5.18.7
  - pnpm-workspace-yaml@1.9.1

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - reselect@5.1.1
  - semver@6.3.1
  - undici-types@6.21.0

shellEmulator: true

packageExtensions:
  dependency-cruiser@*:
    dependencies:
      typescript: npm:@typescript/typescript6@^6.0.2

allowBuilds:
  esbuild: true
  msw: true
  simple-git-hooks: true
  storybook-addon-react-router-v6: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - msw
  - simple-git-hooks
  - storybook-addon-react-router-v6
  - unrs-resolver
