import { z } from 'zod'

/**
 * ✅ DX Best practice (Type safe)
 *
 * Validate api dto by zod
 * See usage example in @/pages/main/api/productPopularListApi.ts
 *
 * Schema autogenerated by ts-to-zod:
 * npx ts-to-zod {path}
 */
export const productDtoSchema = z.object({
  id: z.number().positive(),
  name: z.string(),
  badge: z.string(),
  subtitle: z.string(),
  discountPrice: z.number().positive().optional(),
  price: z.number().positive(),
  // Relative paths, e.g. `/images/content/air-max-pulse.png`, not absolute urls
  imageUrl: z.array(z.string()),
})

export type ProductDto = z.infer<typeof productDtoSchema>
