import { z } from 'zod'

/**
 * ✅ DX Best practice (Type safe)
 *
 * Validate api dto by zod
 * See usage example in @/entities/product/api/productApi.ts
 *
 * Schema autogenerated by ts-to-zod:
 * npx ts-to-zod {path}
 */
export const productDtoSchema = z.object({
  id: z.number().positive(),
  name: z.string(),
  description: z.string(),
  subtitle: z.string(),
  discountPrice: z.number().positive().optional(),
  price: z.number().positive(),
  imageUrl: z.array(z.string().url()),
})

export type ProductDto = z.infer<typeof productDtoSchema>
